import type { Metadata } from "next";
import localFont from "next/font/local"; // Next.js local font setup
import "./globals.css";
import "@fortawesome/fontawesome-free/css/all.min.css"; // Import Font Awesome locally

// Load local fonts using Next.js's localFont API
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans", // Custom property for this font
  weight: "100 900", // Weight range for this font
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono", // Custom property for this font
  weight: "100 900", // Weight range for this font
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children} {/* Render children content here */}
      </body>
    </html>
  );
}
